---
micronaut:
    application:
        name: micronautjpa
    server:
        port: 1919
        cors:
            enabled: true
---
datasources:
  default:
    url: jdbc:postgresql://localhost/survey
    pooled: true
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ''
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update