---
micronaut:
    application:
        name: micronautgorm
    server:
        port: 1919
        cors:
          enabled: true

---
hibernate:
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: true
    use_query_cache: false
    # region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
dataSource:
  url: jdbc:postgresql://localhost/survey
  pooled: true
  driverClassName: org.postgresql.Driver
  username: postgres
  password: ''
